# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_calendar.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('datetime', models.DateTimeField()),
                ('location', models.TextField(max_length=250)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_calendar.CCalendar')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_calendar.Campus')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_of', models.ManyToManyField(to='campus_calendar.Organization')),
                ('main_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_calendar.Campus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_calendar.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'campus')]),
        ),
        migrations.AlterUniqueTogether(
            name='ccalendar',
            unique_together=set([('name', 'campus')]),
        ),
    ]
