# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
    ]
